### ISSUE TITLE
Timeline year/decade/millenia selector does nothing

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/wa-chronos-bugtracker#10]
**World Anvil Username**:
Toblin
**Chronicle Title**:
Test History
**Chronos System**
?
**Describe the Issue**
The selector for Days, Weeks, Months, Years etc does nothing visually.

**To Reproduce**
1. Go to Chronos
2. Change the selector

**Expected behavior**
The timeline display at the very bottom, listing the years, should change to reflect what is being displayed. Right now it remains static with no change. It does appear to change the ACTUAL timeline, as events can disappear on shifting this selector. Still, the year display should update to reflect the span of time being displayed.

**Comment by Xuroth** [comment]
Yes, I see what you mean. The values are changing, and the timeline display is updating, but the presentation can be improved, both in terms of the UTD bar at bottom, as well as the separation of units. I need to rethink how the UTD bar is generated so that it is more clear and "accurate"

**Comment by Xuroth** [comment]
I'm closing this, as the actual "bug" regarding the lack of update was do a previously-resolved issue. However, the context-sensitive counting (marking transitions) is a separate "enhancement" that can be suggested later.
