### ISSUE TITLE
Event displays no date information

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/wa-chronos-bugtracker#12]
**World Anvil Username**:
Toblin
**Chronicle Title**:
Test History
**Chronos System**
?
**Describe the Issue**
When displaying an event, there is no time or date information displayed.

**To Reproduce**
1. Create an event
2. Click the event in the timeline
3. Your title and description is displayed, but no time information

**Expected behavior**
There should be a marker for which time the event begins and when it ends in the display, similar to the old timeline system.
![ksnip_20210611-115703](https://user-images.githubusercontent.com/79937532/121669294-77eae300-caac-11eb-8a07-547730924a29.png)
![ksnip_20210611-115913](https://user-images.githubusercontent.com/79937532/121669299-78837980-caac-11eb-9518-b2d723d1b416.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Xuroth** [comment]
The dates have been added to the Event Popup (when you click an Event on the Timeline) and the Sidebar (when viewing details about an Event). Currently it uses a default 'mask' to mutate the date into a "friendly" string. In the future, a custom 'mask' option will be available to configure the display of the Event's date(s).

I'm closing this issue for now, as the basic support and display is implemented (as of next update).
