### ISSUE TITLE
Cannot scroll past year 0 in reverse

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/wa-chronos-bugtracker#15]
**World Anvil Username**:
Toblin
**Chronicle Title**:
Test History
**Chronos System**
Timeline Display
**Describe the Issue**
When having created a timeline that begins at an internal era of "year 0", there is no way to scroll past year 0 into the past. This may be intentional, as year 0 is the creation of the world, however, this is not obvious to the user, and they may create their timeline with a reference frame of "current" era, and thus have a different year 0 than "Absolute World Creation 0". 

**To Reproduce**
1. Create a timeline
2. Try to scroll past 0 in reverse

**Expected behavior**
A more concise explanation of what Year 0 represents, and a manager for adding Eras and reset time-counting.

**Comment by Kordishal** [comment]
As far as I understood it, eras will be added  but are not yet implemented. So I think once that is the case it will be clearer that year 0 is just the beginning of time. Whatever that might be
