### ISSUE TITLE
New Chronos Event Image

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/wa-chronos-bugtracker#2]
**World Anvil Username**:

Graylion

**Chronicle Title**:

Greyhawk Chronicle

**Chronos System**

**Describe the Issue**

Event cover image does not save, stick or display.

**To Reproduce**

Create a new event
Select an image
Save
View the event
No image is present

**Comment by Xuroth** [comment]
Yes, the Cover Images being used on various things are not displaying properly (though I do believe they are being saved). I need to adjust things so the covers are used (and filesize limits are raised to correct levels)

**Comment by Kordishal** [comment]
10MB would be the correct file size for cover imgaes at least. Guild members only get 25MB for map images. So I don't think we need more than 10 MB (thats probably too big anyway...)

**Comment by Kordishal** [comment]
duplicates #21
