### ISSUE TITLE
Deleting every image in a Chronicle, then not uploading any new ones, makes the Chronicle entirely inaccessible

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/wa-chronos-bugtracker#23]
**World Anvil Username**: iAmTheTot

**Chronicle Title**: This is just a test 

**Chronos System**

**Describe the Issue**
If you delete every image associated with a Chronicle, then do not upload a new one before refreshing/exiting and re-entering, then the chronicle becomes entirely inaccessible and just loads as a completely blank white page.

The real problem may be less than every image, it may simply be deleting your last remaining map and not uploading a new one.

**To Reproduce**
Make a new Chronicle.
Complete the intro, uploading an image.
Go to manage images and delete every image you have.
Do not upload any new images while in this screen.
Refresh, or exit the chronicle and try to reload it.
Page will attempt to load for a moment (some UI visible briefly) before it will all go to a white screen.

**Expected behavior**
Perhaps a warning that does not allow you to delete your last image (or map specifically). Or re-prompt the intro when loading into a chronicle with no images/maps.

**Screenshots**
![3wn5NDY](https://user-images.githubusercontent.com/53080404/121782616-a24da680-cb67-11eb-89d1-f1804c127853.gif)

**Comment by Xuroth** [comment]
Yes, yes this makes sense. I forgot to account for the fact that an item configured for an image will still attempt to load the non-existent image... I'll add fallbacks to use the default cover if an image is missing, or fallback to the standard WA missing-image-cover as a final resort.

Thanks for reporting!
