### ISSUE TITLE
Timeline bars do not show up until refresh of the browser after creating the first timeline

### ISSUE THREAD

**Issue by eccbooks** [worldanvil/wa-chronos-bugtracker#25]
**World Anvil Username**: eccbooks

**Chronicle Title**: Test

**Chronos System**

**Describe the Issue**
After setting up a Chronicle and adding a timeline, I am unable to add events. The timeline piece, which shows up fine in Chrome on my Mac, didn't show up in Safari at all when I tried it there. 

**Screenshots**
<img width="1552" alt="Screen Shot 2021-06-14 at 11 54 47 AM" src="https://user-images.githubusercontent.com/83819488/121922623-2343a400-cd08-11eb-97b2-b5d93f7b6141.png">

**Comment by eccbooks** [comment]
At the suggestion of Lyraine on the Discord channel, I hit refresh (don't know why I didn't think of that) and it is appearing now.

**Comment by Lyraine-Alei** [comment]
On Firefox, had this issue back on Friday, haven't tested yet since as I'd been busy with managing a campaign. XD (Was also fixed with a page reload)

**Comment by eccbooks** [comment]
Thanks for updating my initial title. The new title makes more sense, given what my WA pals helped me figure out.
