### ISSUE TITLE
Timeline numbers can only be clicked to navigate in the right-most part

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/wa-chronos-bugtracker#27]
**World Anvil Username**: SoulLink

**Chronos System**: Timeline Radio Dial

**Describe the Issue**
Navigation in the radio dial of the timeline can be done via clicking the left or right arrows, by drag & drop or by clicking the time unit scale.

The scale, however, can only be clicked in the right-most part of it. 

**Expected behavior**
It would be useful to be able to move the red line to a specific time unit anywhere on the timeline dial. Additionally when clicking the resulting position is way too low. It appears that the clickable area is in the wrong position.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

This is the part I mean to click on.
![image](https://user-images.githubusercontent.com/14262536/123284805-d2ecf300-d50c-11eb-92af-d7bbdb26468e.png)

**Comment by Xuroth** [comment]
The numbers aren't normally clickable. I feel like the behavior of the timeline moving was due to the granularity menu displaying invisibly at the time this report was made (got lost in backlog). Closing as the numbers should not (by current design) trigger any navigation along the timeline.
