### ISSUE TITLE
Back to WA button

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/wa-chronos-bugtracker#28]
**World Anvil Username**: KajetanWrites

**Chronos System**

**Describe the Issue**
Currently you need to use either browser back button or type the world anvil address again to go back to main website. It would be nice to have a back to WA button. (or at least make it more obvious that the world name is the link)

**Comment by Kordishal** [comment]
The red box with the world name in it is a button now. The one at the top of the screen.

**Comment by KajetanWrites** [comment]
Will it change in the future? If not, I think it should made more obvious

**Comment by Kordishal** [comment]
Its the same on the map? It got the name of the World. Thats a fairly common thing to have the name of the world be a link to the world.

**Comment by KajetanWrites** [comment]
ok
