### ISSUE TITLE
Can't create a new chronicle

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/wa-chronos-bugtracker#35]
**World Anvil Username**: KajetanWrite

**Chronicle Title**: World History (world: Veneficia)

**Chronos System**

**Describe the Issue**
When creating a new chronicle I go through the setup, but when I reach finish and save button nothing happens when I click it. After closing the setup window I'm back to the screen which appears after opening a new chronicle from WA

**Comment by iamromeo** [comment]
Not something to report here - this is an Alchemist feature, report to Xuroth on Discord

**Comment by Kordishal** [comment]
Does this still happen?
