### ISSUE TITLE
Chronos: Chronicle renaming does only work partially

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/wa-chronos-bugtracker#37]
**World Anvil Username**: Tillerz

**Chronicle Title**: Alana (https://www.worldanvil.com/w/alana/chronicle/boresia-chronicle)

**Chronos System**

**Describe the Issue**
If you rename a chronicle, the name in the URL stays the same (basically the SLUG). This will confuse a lot of people. I renamed my chronicle to Alana, but it's still https://www.worldanvil.com/w/alana/chronicle/boresia-chronicle

**To Reproduce**
1. Create chronicle
2. Rename it

**Expected behavior**
Chronicle URL should reflect the name change.

**Screenshots**
![image](https://user-images.githubusercontent.com/63370525/126877320-f5d14401-b578-4651-9307-c03c1527ee41.png)

**Comment by Xuroth** [comment]
Tillerz, I believe this is resolved, can you confirm or refute? (I'm able to change name and the slug updates now, but it's been so long since I looked at it, I just want to be extra sure it's working before I close this!)

**Comment by Xuroth** [comment]
I've been able to consistently change and update the name and slug fine, across multiple Chronicles (old and new), so I'm marking this closed. Feel free to get in touch if it doesn't seem to be working for you!
