### ISSUE TITLE
Request: Choose how many lanes a timeline has

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/wa-chronos-bugtracker#43]
**World Anvil Username**: iAmTheTot

**Chronicle Title**: N/A

**Chronos System**

**Describe the Issue**
Being able to choose how many lanes a timeline has would be a big improvement in how users can customize their chronicles. Even if you had to cap it at 4, being able to *reduce* means I could create 5 timelines each with 1 lane and simulate a 5-lane timeline for my chronicle.

**Comment by Xuroth** [comment]
This is added as a potential upcoming feature (pending discussion of implementation and such). Closing the issue here!
