### ISSUE TITLE
Red Date vs Event Dates

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/wa-chronos-bugtracker#45]
**World Anvil Username**:

Grayliom

**Chronicle Title**:

Greyhawk

**Chronos System**

**Describe the Issue**
Red display date appears to be off by 85 years from event dates 

**Screenshots**
![20210922_070612.jpg](https://user-images.githubusercontent.com/79761754/134333696-c6eccf84-33dd-4203-8561-4176c4a993ad.jpg)

![20210922_070600-1.jpg](https://user-images.githubusercontent.com/79761754/134333710-0009d36c-9b53-4a96-892e-b51dbbae5b50.jpg)

![20210922_070548-1.jpg](https://user-images.githubusercontent.com/79761754/134333722-5ce890a5-1b45-43ec-89a8-3f46221ca2b7.jpg)

**Comment by KajetanWrites** [comment]
For me it appears to be by 30 years, but only in one chronicle. Other are ok
