### ISSUE TITLE
Event Date

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/wa-chronos-bugtracker#47]
**World Anvil Username**:

Graylion

**Chronicle Title**:

Ptolus

**Chronos System**

Events

**Describe the Issue**
I tried to create a new event. The default year starts at 0 (odd). And I cannot type the year in 721, as the keyboard does not trigger. If I pop the selector I can scroll the years to the date, however it will take 721 arrow presses to get me there. I must be missing something. 

* Default event year does not respect the starting date established in timeline setup.
* Default year can not be edited, so togo from 0 to 721 requires 721 arrow touches.

**Screenshots**
![20210923_142256.jpg](https://user-images.githubusercontent.com/79761754/134636848-639e2a88-6421-4c9c-b7ce-a9a757829358.jpg)

![20210923_142237.jpg](https://user-images.githubusercontent.com/79761754/134636862-979c0a46-a2ce-41a9-9302-5678e7b44454.jpg)

**Comment by Xuroth** [comment]
Fixed in latest update!
