### ISSUE TITLE
Make timeline section height configurable

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/wa-chronos-bugtracker#5]
**World Anvil Username**: SoulLink

**Chronos System** Core

**Describe the Issue**
On large screens and without a map chronos takes up only a tiny portion of the screen. It would be useful to be able to adjust the heigh tof the timeline container.

Bonus to would be to add more lanes.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Xuroth** [comment]
This is added to the upcoming potential feature list, so I'm closing this here!
