### ISSUE TITLE
First map in list is loaded instead of the selected one when making a change

### ISSUE THREAD

**Issue by mfcarbo-author** [worldanvil/wa-chronos-bugtracker#50]
**World Anvil Username**: mfcarbo

**Chronicle Title**: https://www.worldanvil.com/w/practice-of-power/chronicle/saylossan-chronicle-chronicle

**Chronos System**
Map manager

**Describe the Issue**
When making a change to a selected map and saving, the first map in the map manager is loaded instead of the selected one.

**To Reproduce**

https://user-images.githubusercontent.com/74458780/134973411-3a60c24a-ec73-41d3-9c7a-0c1bfbb14644.mov

**Expected behavior**
I expected the map that was edited to be loaded when I save.

**Comment by Xuroth** [comment]
There was a lot of work put into overhauling how maps and markers are rendered, as well as how the state of the "current active map" is configured. I'm no longer able to reproduce this issue, so I am marking it closed. If the issue persists after the latest update (March 24th 2022), feel free to re-open or comment.
