### ISSUE TITLE
Map markers don't indicate on which map they are located (or the markers are duplicating)

### ISSUE THREAD

**Issue by mfcarbo-author** [worldanvil/wa-chronos-bugtracker#51]
**World Anvil Username**: mfcarbo

**Chronicle Title**: https://www.worldanvil.com/w/practice-of-power/chronicle/saylossan-chronicle-chronicle

**Chronos System**
events and maps

**Describe the Issue**
I'm not sure what the expected behavior is. I have 3 maps and had to recreate markers for the same locations. The event gets linked to a marker on a specific map. However, in the map marker dropdown I now have multiple entries and I can't tell which map the markers are associated with.

**To Reproduce**
1. Select an event and click edit.
2. Click on display.
3. Scroll down to map marker.
4. Click on the field to see the dropdown.

**Expected behavior**
I kind of like that a marker is associated with a specific map. On the other hand, I can see this being problematic if you have the same location on many maps and it needs to be recreated manually for each map. My initial expectation was that there was a collection of map markers I could use across maps.

I think at a minimum knowing which map the marker is associated with would be helpful.

**Screenshots**
![image](https://user-images.githubusercontent.com/74458780/134975896-21111b9b-223e-4996-89b1-12fa6ab65b48.png)

**Comment by Xuroth** [comment]
Map Markers list now shows the name of the map they are linked to!
