### ISSUE TITLE
Day is reduced by 1 on setting/editing

### ISSUE THREAD

**Issue by kjanowski** [worldanvil/wa-chronos-bugtracker#52]
**World Anvil Username**:
Kaleidechse

**Chronicle Title**:
Chronicle of the Nimýric Empire

**Describe the Issue**
When an event is created or its date is changed, the day's number is 1 less than selected. The only exception is the very first day of the entire timeline.

**To Reproduce**
1. Create a new event.
2. Select a start date that is not the first day of the timeline.
3. See the "start date" field display the day before the selected date.
4. Select the intended start date again.
5. See the "start date" field display the intended date.
6. Save the event.
7. Select the created event.
8. See the date display the day before the intended date.
9. Open the event for editing.
10. See the "start date" field display the day before the intended date.
11. Optional: Repeat steps 4 to 8.

**Expected behavior**
The day should be the same as the selected one in all cases. 

**Screenshots**
![chronos_dayBug](https://user-images.githubusercontent.com/8113752/135167623-9f3268d5-116c-4bb8-b300-93316cd2babc.png)

**Comment by kjanowski** [comment]
Update: This bug affects the end date in the same way.

**Comment by Xuroth** [comment]
This should be resolved. Existing chronicles *may* have some issues with dates, but new Chronicles should work fine. You can try editing and re-selecting the date (then save) as a potential workaround.
