### ISSUE TITLE
Image Manager / Editor issues

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/wa-chronos-bugtracker#53]
**World Anvil Username**: SoulLink

**Chronicle Title**: History 

New Chronicle!

**Describe the Issue**
1. The Image Manager has a lot of white space between tiny images. 

2. When uploading a new image it is possible to select multiple, but only the first one is uploaded.

3. When editing an image the image is not actually displayed.

**Comment by Xuroth** [comment]
Should be resolved in latest update
