### ISSUE TITLE
Changing date save button not visible when first opening the popup

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/wa-chronos-bugtracker#55]
**World Anvil Username**: SoulLink

**Chronos System**

**New Chronicle or Existing? (Chronicle created before March 16 2022)**: New

**Describe the Issue**
Not sure if this affects all screen sizes, but at on mine the Set Date save button is not visible when editing the starting date of an event. This is why I didn't realize I had to save the selection before it was actually added to the event. It is necessary to scroll down to save the date. It would probably be better if the full popup were visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/158660989-11c20f04-d15f-4451-becc-d1900d346fcd.png)

**Comment by Xuroth** [comment]
I've added a UX tweak to auto scroll the datepicker into view, so it should be more apparent.
