### ISSUE TITLE
Chronicles, Event Creation: Color Picker predefined Fields switch positions when clicked

### ISSUE THREAD

**Issue by mDehning** [worldanvil/wa-chronos-bugtracker#57]
**World Anvil Username**:
Vertixico

**Feature**: 
Alchemist. Chronicles.
Event Creation, Color Picker

**Describe the Issue**
Using predefined colors in the color picker causes the color fields to switch places seemingly randomly.
![colorPicker_bug](https://user-images.githubusercontent.com/31063219/158692754-1787e459-55c2-4c6e-8928-8e581b505179.gif)

**Comment by Kordishal** [comment]
How is this random? The most recently clicked is sent to the front of the line and everything in between is moved to the right.

**Comment by mDehning** [comment]
Ah I was obviously too tired to see this pattern.

I see you closed this ticket - Are you telling me this is *intended*? I see no indications of pull requests or commits to solve this

**Comment by Kordishal** [comment]
Its a list of the most recent colours you used. When you select a new colour it is added to the list. I don't see how that could not be intended.

And this is just the bug tracker, the code is somewhere else, so there wouldn't be any commits / pull requests here anyway.
