### ISSUE TITLE
Creating a new calendar with Golarion chosen gives default Gregorian months

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/wa-chronos-bugtracker#58]
**World Anvil Username**:
Hanhula

**Chronicle Title**:
Test Chronicle 2

**Chronos System**

**New Chronicle or Existing? (Chronicle created before March 16 2022)** New

**Describe the Issue**
A clear and concise description of what the issue is.
Created a new PF chronicle only to find that *gasp* the months were Earth's!

**To Reproduce**
1. Create a new chronicle
2. In the initial menu, select Golarion Absalom
3. Press next twice

**Expected behavior**
The months should instead be Golarion's months 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/22137517/158745364-dc51754a-dbc1-47e3-8c60-db0c094d0168.png)

**Comment by Xuroth** [comment]
Added a sanity check, and now the calendar should update when you select a different template. I test primarily with Gregorian, and didn't realize the form state wasn't working well. Should be resolved now!
