### ISSUE TITLE
Cannot save change in starting date 

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/wa-chronos-bugtracker#59]
**World Anvil Username**: Hanhula

**Chronicle Title**: Test Chronicle 2

**Chronos System**

**New Chronicle or Existing? (Chronicle created before March 16 2022)** New

**Describe the Issue**
A clear and concise description of what the issue is.
Can't change the starting date of my chronicle; stays as 0.

**To Reproduce**
1. Go to Chronicle Settings
2. Click on Time & Date
3. Click into Starting Date and type a new starting year
4. Either press Enter or click out of the menu and press Save
5. Chronicle will update according to notification, but not actually update. Reopening the menu has returned the starting date to 0

**Expected behavior**
I expected the starting date to change

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![](https://i.imgur.com/4zeGdXW.gif)
Gif of the process.

![](https://i.imgur.com/6uYu8vh.png)
Noting that the group in console is saying 0 for the updated year, too.

**Comment by Kordishal** [comment]
You have to save the starting date after selecting it. To see the save button you have to scroll down. 

See #55

**Comment by Hanhula** [comment]
Ah, so pressing Enter doesn't actually set the date, nor does pressing save - you actually have to hit "set date". Yeah, could use a UX improvement there.
