### ISSUE TITLE
Clicking the Display tab of a new event crashes Chronos on first load 

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/wa-chronos-bugtracker#61]
**World Anvil Username**: Hanhula

**Chronicle Title**: Test Chronicle 3

**Chronos System**

**New Chronicle or Existing? (Chronicle created before March 16 2022)** New

**Describe the Issue**
On the first load of a chronicle (issue seems to resolve on subsequent loads), you cannot view the Display tab of event creation without Chronos entirely crashing to a white screen.

**To Reproduce**
1. Create a new chronicle
2. Set up the chronicle, timelines and all
3. Right-click on a timeline and create new event
4. Filling in details on the first tab of the create event popup is optional
5. Press Display
6. Page crashes, witness error.

**Expected behavior**
Page should not crash when hitting Display; should behave the same as it does on later refreshes.

**Screenshots**
![](https://i.imgur.com/ZRSJzBG.gif)

**Comment by Xuroth** [comment]
This was a D'oh! for me. Resolved in latest update!
