### ISSUE TITLE
Adding related articles to existing events doesn't add a link on the full view of event

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/wa-chronos-bugtracker#63]
**World Anvil Username**: KajetanWrites

**Chronicle Title**: Chronicle of the invasion and occupation

**Chronos System**

**New Chronicle or Existing? (Chronicle created before March 16 2022)**
New

**Describe the Issue**
When you add a related article when creating new event everything works fine, but when you add one to an exisiting event it doesn't show on the full view of the event (after clicking read more). Closing and opening the chronicle doesn't solve the issue

**Comment by Xuroth** [comment]
This was due to parts of the app not updating when the event was saved. This should be resolved in the latest update! If the issue persists, feel free to reopen or comment!
