### ISSUE TITLE
Manually Setting Dates

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/wa-chronos-bugtracker#66]
**World Anvil Username**:

Graylion

**Chronicle Title**:

Ptolus Chronicle

**Chronos System**

Events

**New Chronicle or Existing? (Chronicle created before March 16 2022)**

Existing

**Describe the Issue**
A clear and concise description of what the issue is.

If my current year is 721 and I need to add historical date 100 or 400 years ago I see no way to do this without clicking the year 100 or 400 times. I'm sure there may be a way, I just don't see it. 

Found it ...

Strangely enough I just figured out if I click on the year I can actually type there!

Freaking amazing!

Not obvious but really amazing..

And now I know how it works.

Bam exit stage left.

**Comment by Xuroth** [comment]
Next update will include a contextual hint that the fields are interactable. (Also, fixes the month selection from just closing the date-picker). Closing this issue!
